name: Run Python Script with Snyk

on:
  push:
    branches:
      - main   # change if needed

jobs:
  snyk-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install dependencies safely
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install snyk smtplib  # extra packages if not listed

      - name: Run Python Script
        run: python your_script.py

      - name: Run Snyk Security Scan
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: test

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Commit Triggered: Python Script & Snyk Scan Completed"
          to: yourmail@example.com
          from: GitHub Actions <${{ secrets.EMAIL_USER }}>
          body: "✅ Python script executed and Snyk scan finished."
