name: Python Script and Snyk Scan with Email

on:
  push:
    branches:
      - main

jobs:
  run-script-and-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Snyk scan
        uses: snyk/actions/python-3.10@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
        continue-on-error: true

      - name: Run Python script with email
        run: python script.py
        env:
          EMAIL_USERNAME: ${{ secrets.EM_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EM_PASSWORD }}
