name: Run Python Script with Snyk

on:
  push:   # triggers whenever a commit is pushed
    branches:
      - main   # or any branch you want

jobs:
  snyk-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Python Script
        run: python script.py

      - name: Run Snyk Security Scan
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: test
          
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp-relay.brevo.com
          server_port: 587
          username: ${{ secrets.EM_USERNAME }}
          password: ${{ secrets.EMA_PASSWORD }}
          subject: "Commit Triggered: Python Script & Snyk Scan Completed"
          to: emmanuel.atitebi06@gmail.com
          from: GitHub Actions <${{ secrets.EM_USERNAME }}>
          body: "Your Python script has run and Snyk scan is completed."
