name: Python Script and Snyk Scan with Email

on:
  push:
    branches:
      - main

jobs:
  run-script-and-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Snyk scan
        uses: snyk/actions/python-3.10@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
        continue-on-error: true

      - name: Run Python script
        run: python script.py

      - name: Send mail
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp-relay.brevo.com
          server_port: 587
          secure: true
          username: ${{ secrets.EM_USERNAME }}  # e.g., your.email@gmail.com
          password: ${{ secrets.EM_PASSWORD }}  # App-specific password for Gmail
          subject: Snyk Scan and Python Script Execution Report
          to: vonstrucker06@gmail.com  # From your earlier question
          from: GitHub Actions <${{ secrets.EM_USERNAME }}>  # Matches MAIL_USERNAME
          body: |
            A new commit was pushed to ${{ github.repository }}.
            Snyk scan completed. Check results: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          priority: normal
          ignore_cert: false
          nodemailerlog: false
          nodemailerdebug: false
